/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '无权限',
      constant: true,
      hideInMenu: true,
      i18nKey: 'route.403'
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '页面不存在',
      constant: true,
      hideInMenu: true,
      i18nKey: 'route.404'
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '服务器错误',
      constant: true,
      hideInMenu: true,
      i18nKey: 'route.500'
    }
  },
  {
    name: 'accounts',
    path: '/accounts',
    component: 'layout.base$view.accounts',
    meta: {
      title: '账号管理',
      icon: 'mdi:account-group',
      order: 2,
      i18nKey: 'route.accounts'
    }
  },
  {
    name: 'data',
    path: '/data',
    component: 'layout.base$view.data',
    meta: {
      title: '数据看板',
      icon: 'mdi:chart-line',
      order: 3,
      i18nKey: 'route.data'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: '外部页面',
      constant: true,
      hideInMenu: true,
      keepAlive: true,
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: '系统设置',
      icon: 'mdi:cog',
      order: 4,
      i18nKey: 'route.settings'
    }
  }
];
